export const portfolioData = {
  personal: {
    name: "Shreya Dubey",
    role: "Software Engineer",
    subtitle: "Backend • Full Stack • AI",
    tagline: "Building scalable software and intelligent systems.",
    description: "I build production-oriented backend systems, full-stack applications, AI/LLM applications, developer tools, and end-to-end products. My work spans backend engineering, system design, and AI infrastructure.",
    email: "dubeyshreya2507@gmail.com",
    linkedin: "https://www.linkedin.com/in/shreya-dubey-544874289/",
    github: "https://github.com/shreyad2806",
    resume: "/SDE.pdf",
    stack: [
      "Backend Engineering",
      "Full Stack",
      "AI Systems",
      "System Design",
      "Developer Tools",
      "Open Source",
    ],
  },

  contact: {
    email: "mailto:dubeyshreya2507@gmail.com",
    linkedin: "https://www.linkedin.com/in/shreya-dubey-544874289/",
    github: "https://github.com/shreyad2806",
    resume: "/SDE.pdf",
  },

  metrics: [
    {
      value: "8+",
      label: "Individual Software Projects",
      caption: "AI • Backend • Full Stack",
      icon: "Layers",
    },
    {
      value: "4+",
      label: "Production-Style Systems",
      caption: "Scalable architectures & developer tools",
      icon: "Boxes",
    },
    {
      value: "20+",
      label: "Technologies Explored",
      caption: "Frameworks, Cloud & AI",
      icon: "Wrench",
    },
    {
      value: "Hackathons",
      label: "SIH Runner-up",
      caption: "ET GenAI Finalist • NandaHack Participant",
      icon: "Trophy",
    },
  ],

  hackathons: [
    {
      icon: "Trophy",
      title: "Smart India Hackathon",
      subtitle: "Runner-up",
    },
    {
      icon: "Rocket",
      title: "ET GenAI Hackathon",
      subtitle: "Finalist",
    },
    {
      icon: "Globe",
      title: "NandaHack",
      subtitle: "AI Infrastructure Exploration",
    },
    {
      icon: "Github",
      title: "Open Source",
      subtitle: "Contributor",
    },
  ],

  projects: [
    {
      id: "talentlens",
      name: "TalentLens",
      description: "Resume intelligence and candidate discovery platform using semantic search, embeddings, vector retrieval, and candidate ranking.",
      tech: ["FastAPI", "Python", "RAG", "Sentence Transformers", "Pinecone", "Semantic Search"],
      github: "https://github.com/shreyad2806/TalentLens",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "ai-tech-stack-recommender",
      name: "AI Tech Stack Recommender",
      description: "Technology stack recommendation platform that analyzes application requirements and recommends suitable technologies and architecture choices.",
      tech: ["FastAPI", "React", "Gemini", "Python", "PostgreSQL"],
      github: "https://github.com/shreyad2806/AI-Tech-Stack-Recommender",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "lawgpt-crm",
      name: "CRM",
      description: "Full-stack CRM and marketing automation platform for lead management, workflow automation, and sales operations.",
      tech: ["Next.js", "TypeScript", "React", "PostgreSQL", "Supabase", "OpenAI", "Automation"],
      github: "https://github.com/shreyad2806/LawGPT-CRM",
      externalLink: "https://drive.google.com/file/d/18RrSipRNnuMleit-CbmXPcd3z_zfen1G/view?usp=sharing",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "complytai",
      name: "ComplytAI",
      description: "Financial compliance and risk intelligence platform using document processing, RAG, semantic search, and CrewAI-based agent orchestration.",
      tech: ["Python", "FastAPI", "CrewAI", "RAG", "Pinecone", "PostgreSQL", "Document Processing"],
      github: "https://github.com/shreyad2806/ComplytAI",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "falcon-airlines",
      name: "Falcon Airlines",
      description: "Full-stack airline reservation and ticketing platform with flight search, booking, payments, ticket generation, and boarding pass functionality.",
      tech: ["Java", "Spring Boot", "React", "PostgreSQL", "REST APIs", "Docker", "JWT", "PDF/QR"],
      github: "https://github.com/shreyad2806/FalconAirlines",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "devforge",
      name: "DevForge",
      description: "Full-stack SaaS platform for discovering, building, and managing reusable developer kits with authentication, subscriptions, and billing.",
      tech: ["Next.js", "TypeScript", "React", "Supabase", "PostgreSQL", "SaaS", "Authentication", "Subscriptions"],
      github: "https://github.com/shreyad2806/DevForge",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "architectiq",
      name: "ArchitectIQ",
      description: "AI-powered software architecture review platform that analyzes repositories, identifies architectural issues, and produces actionable engineering insights.",
      tech: ["Python", "FastAPI", "Repository Analysis", "System Design", "OpenAI", "Code Intelligence"],
      github: "https://github.com/shreyad2806/ArchitectIQ",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "reflex-ninja",
      name: "Reflex Ninja",
      description: "Native Android reflex game built with Kotlin, featuring timed gameplay, scoring, and interactive game mechanics.",
      tech: ["Kotlin", "Android", "Android Studio", "Game Development"],
      github: "https://github.com/shreyad2806/Reflex-Ninja",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "kodexa",
      name: "Kodexa",
      description: "AI developer tool for turning agent-generated and rapidly evolving codebases into reusable, maintainable software through debugging, codebase analysis, and repository intelligence.",
      tech: ["Python", "FastAPI", "LangGraph", "PostgreSQL", "pgvector", "Developer Tools", "Repository Intelligence"],
      github: "https://github.com/shreyad2806/Kodexa",
      caseStudy: null,
      featured: true,
      status: "In Progress",
    },
  ],

  currentFocus: {
    title: "Kodexa",
    subtitle: "AI-Powered Developer Tool",
    description: "Building an AI-powered developer tool for repository intelligence, debugging, code comprehension, and context-aware engineering workflows.",
    badge: "Active Development",
  },

  developerJournal: {
    title: "Articles Coming Soon",
    articles: [
      { title: "Building TalentLens", category: "Case Study", readTime: "12 min" },
      { title: "AI Architecture Review", category: "Engineering", readTime: "8 min" },
      { title: "Understanding AI Infrastructure", category: "Architecture", readTime: "10 min" },
      { title: "Lessons from NandaHack", category: "Hackathon", readTime: "6 min" },
    ],
    note: "Documenting my learning journey as I build production software and intelligent systems.",
  },

  blog: {
    title: "Developer Journal",
    readingTime: "",
    href: null,
  },

  technicalExpertise: [
    {
      icon: "Cpu",
      category: "Core CS",
      skills: [
        "Data Structures & Algorithms",
        "OOP",
        "DBMS",
        "Operating Systems",
        "Computer Networks",
        "System Design",
      ],
    },
    {
      icon: "Code",
      category: "Languages",
      skills: ["Java", "Python", "C++", "JavaScript", "TypeScript", "SQL"],
    },
    {
      icon: "Server",
      category: "Backend",
      skills: [
        "Spring Boot",
        "Spring Data JPA",
        "Hibernate",
        "JDBC",
        "FastAPI",
        "REST APIs",
        "Microservices",
        "Authentication",
      ],
    },
    {
      icon: "Layout",
      category: "Frontend",
      skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    },
    {
      icon: "Brain",
      category: "AI & Intelligent Systems",
      skills: [
        "LLMs",
        "Generative AI",
        "RAG",
        "AI Agents",
        "LangChain",
        "LangGraph",
        "CrewAI",
        "Semantic Search",
        "Embeddings",
        "Prompt Engineering",
      ],
    },
    {
      icon: "Database",
      category: "Databases & Infrastructure",
      skills: [
        "PostgreSQL",
        "MySQL",
        "Redis",
        "Pinecone",
        "Docker",
        "Linux",
        "Git",
        "GitHub",
        "CI/CD",
        "AWS",
      ],
    },
  ],
};
