export const portfolioData = {
  personal: {
    name: "Shreya Dubey",
    role: "Software Engineer",
    subtitle: "Backend • Full Stack • AI",
    tagline: "Building scalable software and intelligent systems.",
    description: "I build production-oriented backend systems, full-stack applications, AI/LLM applications, developer tools, and end-to-end products. My work spans backend engineering, system design, and AI infrastructure.",
    email: "dubeyshreya2507@gmail.com",
    linkedin: "https://www.linkedin.com/in/shreya-dubey-544874289/",
    github: "https://github.com/shreyad2806",
    resume: "/SDE.pdf",
    stack: [
      "Backend Engineering",
      "Full Stack",
      "AI Systems",
      "System Design",
      "Developer Tools",
      "Open Source",
    ],
  },

  contact: {
    email: "mailto:dubeyshreya2507@gmail.com",
    linkedin: "https://www.linkedin.com/in/shreya-dubey-544874289/",
    github: "https://github.com/shreyad2806",
    resume: "/SDE.pdf",
  },

  metrics: [
    {
      value: "8+",
      label: "Individual Software Projects",
      caption: "AI • Backend • Full Stack",
      icon: "Layers",
    },
    {
      value: "4+",
      label: "Production-Style Systems",
      caption: "Scalable architectures & developer tools",
      icon: "Boxes",
    },
    {
      value: "20+",
      label: "Technologies Explored",
      caption: "Frameworks, Cloud & AI",
      icon: "Wrench",
    },
    {
      value: "Hackathons",
      label: "SIH Runner-up",
      caption: "ET GenAI Finalist • NandaHack Participant",
      icon: "Trophy",
    },
  ],

  hackathons: [
    {
      icon: "Trophy",
      title: "Smart India Hackathon",
      subtitle: "Runner-up",
    },
    {
      icon: "Rocket",
      title: "ET GenAI Hackathon",
      subtitle: "Finalist",
    },
    {
      icon: "Globe",
      title: "NandaHack",
      subtitle: "AI Infrastructure Exploration",
    },
    {
      icon: "Github",
      title: "Open Source",
      subtitle: "Contributor",
    },
  ],

  projects: [
    {
      id: "talentlens",
      name: "TalentLens",
      description: "AI-powered resume intelligence and candidate search platform using hybrid retrieval, semantic search, embeddings, vector search, filtering and recruiter analytics.",
      tech: ["Python", "FastAPI", "RAG", "BM25", "Semantic Search", "Pinecone", "Sentence Transformers"],
      github: "https://github.com/shreyad2806/TalentLens",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "ai-tech-stack-recommender",
      name: "AI Tech Stack Recommender",
      description: "LLM-powered platform that recommends complete technology stacks, software architecture, deployment strategy and development roadmap from a natural language project idea.",
      tech: ["FastAPI", "React", "Gemini", "Python", "PostgreSQL", "JWT Authentication", "Google Gemini", "Tailwind CSS"],
      github: "https://github.com/shreyad2806/AI-Tech-Stack-Recommender",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "lawgpt-crm",
      name: "LawGPT CRM",
      description: "AI-powered CRM and marketing automation platform for lead discovery, qualification, content generation, market insights and analytics.",
      tech: ["Next.js", "PostgreSQL/Supabase", "AI", "workflow automation"],
      github: "https://github.com/shreyad2806/LawGPT-CRM",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "complytai",
      name: "ComplytAI",
      description: "AI-powered financial compliance and risk intelligence platform using document analysis, RAG, vector search, agent/workflow orchestration, and structured compliance reporting.",
      tech: ["Python", "FastAPI", "LangGraph", "CrewAI", "PostgreSQL", "Pinecone", "RAG"],
      github: "https://github.com/shreyad2806/ComplytAI",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "falcon-airlines",
      name: "Falcon Airlines",
      description: "Enterprise airline reservation system with authentication, booking, ticketing, payments, passenger management, caching, and CI/CD.",
      tech: ["Java 21", "Spring Boot", "Spring Security", "PostgreSQL", "Redis", "Docker", "JWT"],
      github: "https://github.com/shreyad2806/Falcon-Airlines",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "devforge",
      name: "DevForge",
      description: "Full-stack SaaS platform for discovering and building developer kits with authentication, dashboards, premium feature gating, billing/subscription flows, and workspace functionality.",
      tech: ["Next.js", "TypeScript", "React", "Supabase", "PostgreSQL", "Tailwind CSS", "Stripe/Polar"],
      github: "https://github.com/shreyad2806/DevForge",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "architectiq",
      name: "ArchitectIQ",
      description: "AI-powered platform that reviews software repositories, analyzes backend architecture, detects design issues, and generates actionable engineering insights.",
      tech: ["Python", "FastAPI", "PostgreSQL", "React", "TypeScript", "AI", "System Design"],
      github: "https://github.com/shreyad2806/ArchitectIQ",
      caseStudy: null,
      featured: true,
      status: "Completed",
    },
    {
      id: "kodexa",
      name: "Kodexa",
      description: "AI-powered developer tool for repository intelligence, debugging, code comprehension, and context-aware engineering workflows.",
      tech: ["Python", "FastAPI", "LangGraph", "PostgreSQL", "VS Code Extension", "LLMs", "Agentic AI"],
      github: "https://github.com/shreyad2806/Kodexa",
      caseStudy: null,
      featured: true,
      status: "In Progress",
    },
  ],

  currentFocus: {
    title: "Kodexa",
    subtitle: "AI-Powered Developer Tool",
    description: "Building an AI-powered developer tool for repository intelligence, debugging, code comprehension, and context-aware engineering workflows.",
    badge: "Active Development",
  },

  developerJournal: {
    title: "Articles Coming Soon",
    articles: [
      { title: "Building TalentLens", category: "Case Study", readTime: "12 min" },
      { title: "AI Architecture Review", category: "Engineering", readTime: "8 min" },
      { title: "Understanding AI Infrastructure", category: "Architecture", readTime: "10 min" },
      { title: "Lessons from NandaHack", category: "Hackathon", readTime: "6 min" },
    ],
    note: "Documenting my learning journey as I build production software and intelligent systems.",
  },

  blog: {
    title: "Developer Journal",
    readingTime: "",
    href: null,
  },

  technicalExpertise: [
    {
      icon: "Cpu",
      category: "Core CS",
      skills: [
        "Data Structures & Algorithms",
        "OOP",
        "DBMS",
        "Operating Systems",
        "Computer Networks",
        "System Design",
      ],
    },
    {
      icon: "Code",
      category: "Languages",
      skills: ["Java", "Python", "C++", "JavaScript", "TypeScript", "SQL"],
    },
    {
      icon: "Server",
      category: "Backend",
      skills: [
        "Spring Boot",
        "Spring Data JPA",
        "Hibernate",
        "JDBC",
        "FastAPI",
        "REST APIs",
        "Microservices",
        "Authentication",
      ],
    },
    {
      icon: "Layout",
      category: "Frontend",
      skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    },
    {
      icon: "Brain",
      category: "AI & Intelligent Systems",
      skills: [
        "LLMs",
        "Generative AI",
        "RAG",
        "AI Agents",
        "LangChain",
        "LangGraph",
        "CrewAI",
        "Semantic Search",
        "Embeddings",
        "Prompt Engineering",
      ],
    },
    {
      icon: "Database",
      category: "Databases & Infrastructure",
      skills: [
        "PostgreSQL",
        "MySQL",
        "Redis",
        "Pinecone",
        "Docker",
        "Linux",
        "Git",
        "GitHub",
        "CI/CD",
        "AWS",
      ],
    },
  ],
};
