import { Project } from "@/types/project";

export const projects: Project[] = [
  // FEATURED PROJECTS
  {
    id: "talentlens",
    name: "TalentLens",
    description: "AI-powered resume intelligence platform using RAG, semantic search, and vector databases to intelligently rank candidates.",
    tech: ["FastAPI", "Python", "Sentence Transformers", "Pinecone", "RAG"],
    thumbnail: "/images/talentlens.png",
    github: "https://github.com/shreyad2806/TalentLens",
    status: "completed",
    slug: "talentlens",
  },
  {
    id: "ai-tech-stack-recommender",
    name: "AI Tech Stack Recommender",
    description: "LLM-powered application that recommends complete technology stacks, architecture, and deployment strategies from a project idea.",
    tech: ["FastAPI", "Gemini", "React", "PostgreSQL"],
    thumbnail: "/images/stackmind.png",
    github: "https://github.com/shreyad2806/Ai-tech-stack-recommender",
    status: "completed",
    slug: "ai-tech-stack-recommender",
  },
  {
    id: "lawgpt-crm",
    name: "LawGPT CRM",
    description: "AI-powered CRM and marketing automation platform with intelligent lead management and workflow automation.",
    tech: ["Next.js", "Supabase", "PostgreSQL", "OpenAI"],
    thumbnail: "/images/crm.png",
    github: "https://github.com/shreyad2806/LawGPT-CRM",
    status: "completed",
    slug: "lawgpt-crm",
  },
  {
    id: "complytai",
    name: "ComplytAI",
    description: "AI-powered financial compliance and risk intelligence platform using RAG pipelines, workflow orchestration, and vector search.",
    tech: ["Next.js", "TypeScript", "Pinecone", "n8n", "Ollama"],
    thumbnail: "/images/complytai.png",
    github: "https://github.com/shreyad2806/ComplytAI",
    status: "completed",
    slug: "complytai",
  },
  {
    id: "kodexa",
    name: "Kodexa",
    description: "Workflow automation platform that connects services, automates repetitive tasks, and reduces manual business operations.",
    tech: ["Python", "n8n", "Docker", "PostgreSQL"],
    thumbnail: "/images/kodexa.png",
    github: "https://github.com/shreyad2806/Kodexa",
    status: "completed",
    slug: "kodexa",
  },
  {
    id: "reflex-ninja",
    name: "Reflex Ninja",
    description: "A native Android reflex game built while learning Kotlin. Players have 15 seconds to tap randomly appearing ninjas while the score updates in real time.",
    tech: ["Kotlin", "SQLite", "Android Studio"],
    thumbnail: "/images/reflexNinja.png",
    github: "https://github.com/shreyad2806/Reflex-Ninja",
    status: "completed",
    slug: "reflex-ninja",
  },
  // CURRENTLY BUILDING
  {
    id: "architectiq",
    name: "ArchitectIQ",
    description: "AI-powered repository architecture review platform that analyzes codebases and provides intelligent software architecture insights.",
    tech: ["Python", "LangGraph", "OpenTelemetry", "AI Review"],
    thumbnail: "/images/architectiq.png",
    github: "https://github.com/shreyad2806/ArchitectIQ",
    status: "in-progress",
    slug: "architectiq",
  },
  // UPCOMING
  {
    id: "contextos",
    name: "ContextOS",
    description: "Context-aware memory infrastructure for intelligent applications. Persistent context, memory orchestration, intelligent retrieval and inference routing.",
    tech: ["GraphRAG", "MCP", "Redis", "Memory"],
    thumbnail: "/images/contextos.png",
    status: "upcoming",
    slug: "contextos",
  },
];

export const categories = [
  "All Projects",
  "AI Systems",
  "RAG",
  "Agents",
  "Automation",
  "Developer Tools",
] as const;
